name: effectivenezz
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.5.6+22

environment:
  sdk: ">=2.3.0 <2.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12+2
  path_provider: ^1.6.22
  flutter_svg: ^0.19.1
  path: ^1.7.0
  share: ^0.6.5+4
  launch_review: ^2.0.0
  intl: ^0.16.1
  flare_flutter: ^2.0.6
  after_layout: ^1.0.7+2
  sqflite: ^1.3.2+1
  flutter_material_color_picker: ^1.0.5
  flutter_duration_picker: ^1.0.4
  fluttertoast: ^7.1.1
  calendar_views: ^0.5.2
  soundpool: ^1.1.3
  google_sign_in: ^4.5.5
  google_sign_in_web: ^0.9.2
  googleapis: ^0.56.1
  googleapis_auth: ^0.2.12
  youtube_player_flutter: ^7.0.0+7
  purchases_flutter: ^1.4.1
  sticky_headers: ^0.1.8+1
  flutter_local_notifications: ^3.0.1+2
  flutter_iconpicker: ^2.2.2
  rxdart: ^0.24.1
  minimize_app: ^0.1.1
  url_launcher: ^5.4.10
  neat_periodic_task: ^1.0.1
  charts_flutter: ^0.9.0
  demoji: ^1.0.1
  flutter_xlider: ^3.4.0
  youtube_explode_dart: ^1.6.2
  uuid: ^2.2.2
  snaplist: ^0.1.8
  sliding_sheet: ^0.4.1
  flutter_expanded_tile: ^0.2.1
  simple_speed_dial: ^0.1.2
  dwds: ^7.0.2
  firebase_remote_config_hybrid: ^0.0.1
  auto_size_text_field: ^0.1.6
  sweetsheet: ^0.2.0
  flutter_launcher_icons: ^0.8.1
  timezone: ^0.5.9
  countdown_flutter: ^0.1.2
  circular_check_box: ^1.0.4
  responsive_builder: ^0.3.0
  package_info: ^0.4.3
  dartx: ^0.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
#    - images/a_dot_burr.jpeg
    - assets/empty_illustration.svg
    - assets/time_doctor/80_20.svg
    - assets/time_doctor/parkinson_law.svg
    - assets/time_doctor/the_art_of_not_doing.svg
    - assets/set_type/type_a.svg
    - assets/set_type/type_b.svg
    - assets/welcome/doctor_illustration.png
    - assets/welcome/metric_illustration.png
    - assets/welcome/planning_illustration.png
    - assets/welcome/time_illustration.png
    - assets/logo.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
